INJECTION_PHRASES = [
    "ignore previous instructions",
    "ignore all previous instructions",
    "act as system",
    "override the prompt",
    "new prompt",
]

OFF_TOPIC_PHRASES = [
    "write me code",
    "generate a script",
    "delete all files from the system",
    "tell me a joke",
    "write malware",
    "build a python program",
    "create a java application",
    "make a web app",
    "implement a function for me",
    "give me a code snippet",
    "write a sorting algorithm",
    "help me debug this code",
    "fix my javascript error",
    "what is the time now?",
    "optimize this function",
    "convert this code to python",
    "generate backend logic",
    "design a database schema",
    "create an api endpoint",
    "write sql queries",
    "generate html and css",
    "build a react component",
    "write a bash script",
    "automate this task using code",
    "generate a dockerfile",
    "write unit tests",
    "what is artificial intelligence",
    "explain machine learning",
    "define blockchain technology",
    "how does the internet work",
    "what is quantum computing",
    "explain relativity",
    "tell me about black holes",
    "what is the capital of germany",
    "who invented the telephone",
    "when was the internet created",
    "explain photosynthesis",
    "what is cloud computing",
    "describe neural networks",
    "what is data science",
    "how does gps work",
    "what can you do",
    "who are you",
    "are you human",
    "how do you work",
    "what model are you",
    "what is your purpose",
    "can you think",
    "do you have emotions",
    "how were you trained",
    "what are your limitations",
    "can you learn from me",
    "what is your architecture",
    "are you conscious",
    "explain yourself",
    "format my computer",
    "hack a website",
    "bypass authentication",
    "crack a password",
    "access private data",
    "disable security features",
    "exploit a vulnerability",
    "gain admin access",
    "break into an account",
    "write a virus",
    "create ransomware",
    "inject malicious code",
    "steal user data",
    "launch a ddos attack",
    "what is the weather today",
    "check temperature outside",
    "what time is it now",
    "set a reminder for tomorrow",
    "book a flight ticket",
    "find nearby restaurants",
    "get directions to mumbai",
    "order food online",
    "track my parcel",
    "check train schedule",
    "find hotels near me",
    "show me travel options",
    "book a cab",
    "find cheapest flights",
    "check traffic conditions",
    "write a poem",
    "compose a song",
    "create a short story",
    "generate a story plot",
    "write a motivational speech",
    "draft a blog post",
    "create a screenplay",
    "write a dialogue",
    "generate a fictional story",
    "write a rap verse",
    "create a horror story",
    "write a romantic story",
    "generate creative content",
    "write a novel intro",
    "compose lyrics",
    "tell me something funny",
    "make me laugh",
    "give me a meme idea",
    "say something cool",
    "entertain me",
    "tell a funny story",
    "make a joke about programmers",
    "say something random",
    "give me a fun fact",
    "tell me a riddle",
    "play a game with me",
    "ask me a quiz question",
    "guess what im thinking",
    "tell me something interesting",
    "say something weird",
]